service: herocast-api-private

plugins:
  - serverless-offline

provider:
  name: aws
  apiKeys:
    - privateKey
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  role: arn:aws:iam::163410335292:role/private-api

  environment:
  #tableName: ${self:custom.tableName}
   #stripeSecretKey: ${self:custom.environment.stripeSecretKey}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:"

functions:
  login:
    handler: auth-api/login.main
    events:
      - http:
          path: login
          method: post
          cors: true
          private: true
        
  signup:
    handler: auth-api/signup.main
    events:
      - http:
          path: signup
          method: post
          cors: true
          private: true

  deleteTimes:
    handler: private-api/delete-times.main
    events:
      - http:
          path: delete-times
          method: post
          cors: true
          private: true

  setDefaultPrices:
    handler: private-api/set-default-prices.main
    events:
      - http:
          path: set-default-prices/
          method: post
          cors: true
          private: true

  updateGameConfig:
    handler: private-api/update-game-config.main
    events:
      - http:
          path: update-games
          method: post
          cors: true
          private: true

  updateConsoleConfig:
    handler: private-api/update-console-config.main
    events:
      - http:
          path: update-console
          method: post
          cors: true
          private: true

  updateTimes:
    handler: private-api/update-times.main
    events:
      - http:
          path: update-times
          method: post
          cors: true
          private: true

  getMyTimes:
    handler: private-api/get-my-times-for-this-date.main
    events:
      - http:
          path: get-my-times
          method: post
          cors: true
          private: true